fun main() {
 println("Set Inmutable")
    val numeros = setOf(1,2,3,4,8,4,1,3)
    println("numeros set: ${numeros}")
 println("Operaciones de conjuntos")
    val pares = setOf(2,4,6,8,10)
    val multiplos3 = setOf(3,6,9,12)
    println("pares set: ${pares}")
    println("multiplos3 set: ${multiplos3}")
    println("union: ${pares union multiplos3}")
    println("interseccion: ${pares intersect multiplos3}")
    println("substraccion: ${pares subtract multiplos3}")
    println("pares set: ${pares}")
    println("multiplos3: ${multiplos3}")
    
 println("Set Mutable")
 val tags = mutableSetOf("bautizo","orden_sacerdotal","matrimonio")
 println(tags)
 tags.add("bautizo")
 println(tags)
 tags.add("orden_sacerdotal")
 println(tags)
 tags.remove("matrimonio")
 println(tags)
 println("Verificar si elemento existe ${"bautizo" in tags}")
 println("Verificar si elemento existe ${"matrimonio" in tags}")
}